apiVersion: apps/v1
kind: Deployment
metadata:
  name: plurall-dashboard
  labels:
    app: plurall-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plurall-dashboard
  template:
    metadata:
      labels:
        app: plurall-dashboard
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: web-files
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-files
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index Dashboard.html;
        try_files $uri $uri/ /Dashboard.html;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: plurall-dashboard-service
spec:
  selector:
    app: plurall-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
